title: Cezary Bartoszuk 
email: cezarybartoszuk@gmail.com
description: >-
  Things most recently learnt.
baseurl: "" # jeśli używasz repozytorium TwojaNazwa.github.io, zostaw puste
url: "" # Twoja domena

# Ustawienia nawigacji (dla motywu Minima i wielu innych)
header_pages:
  - index.md
